// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAwsJZPdBhSoK95DtkSYQN3ujJkA4bZ0',
    appId: '1:424026517977:web:098dad48bd048ba04a29c8',
    messagingSenderId: '424026517977',
    projectId: 'logintest-221d3',
    authDomain: 'logintest-221d3.firebaseapp.com',
    storageBucket: 'logintest-221d3.appspot.com',
    measurementId: 'G-LC57T74ZXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG_ZulI6ykaewn5pYeyuCpYLSyTdp2buo',
    appId: '1:424026517977:android:1fbc1785579bfbc54a29c8',
    messagingSenderId: '424026517977',
    projectId: 'logintest-221d3',
    storageBucket: 'logintest-221d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-NJrphIlxoGP0rdWyswSC2xADKB4Ze4',
    appId: '1:424026517977:ios:b595253d8d26a1464a29c8',
    messagingSenderId: '424026517977',
    projectId: 'logintest-221d3',
    storageBucket: 'logintest-221d3.appspot.com',
    iosBundleId: 'com.example.sabee',
  );
}
